apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-analytics.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ include "cost-analytics.name" . }}-backend
  ports:
      - port: {{ .Values.backend.service.port }}
        targetPort: {{ .Values.backend.service.port }}
